--- 
title: "RStudio Server Professional Edition"
subtitle: "Administation Guide"
date: "`r Sys.Date()`"
knit: bookdown::render_book
output:
  bookdown::gitbook: 
    html_names: "chapter"
    config:
      edit:
        link: https://github.com/jjallaire/rsp-admin-guide/edit/master/%s
        text: "Edit"
      download: ["pdf"]
      toolbar:
        position: fixed
      toc:
        collapse: yes
        scroll_highlight: yes
        before: |
          <li><a href="./">RStudio Server Professional</a></li>
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
      before_body: cover.tex
    keep_tex: no
    latex_engine: xelatex
    pandoc_args: [
      "--variable", "title="
    ]
documentclass: book
classoption: oneside
geometry: margin=1in
fontsize: 11pt
---

# Getting Started

RStudio Server enables you to provide a browser based interface (the RStudio IDE) to a version of R running on a remote Linux server. Deploying R and RStudio on a server has a number of benefits, including:

- The ability to access R sessions from any computer in any location;
- Easy sharing of code, data, and other files with colleagues;
- Allowing multiple users to share access to the more powerful compute resources (memory, processors, etc.) available on a well equipped server; and
- Centralized installation and configuration of R, R packages, TeX, and other supporting libraries.

This manual describes *RStudio Server Professional Edition*, which adds many enhancements to the open-source version of RStudio Server, including:

- The ability to run multiple concurrent R sessions per-user.
- Flexible use of multiple versions of R on the same server.
- Project sharing for easy collaboration within workgroups.
- Load balancing for increased capacity and higher availability.
- An administrative dashboard that provides insight into active sessions, server health, and monitoring of system-wide and per-user performance and resource metrics;
- Authentication using system accounts, ActiveDirectory, LDAP, or Google Accounts;
- Full support for PAM (including PAM sessions for dynamically provisioning user resources);
- Ability to establish per-user or per-group CPU priorities and memory limits;
- HTTP enhancements including support for SSL and keep-alive for improved performance;
- Ability to restrict access to the server by IP;
- Customizable server health checks; and
- Suspend, terminate, or assume control of user sessions; Impersonate users for assistance and troubleshooting.




